config/routes.rb
Rails.application.routes.draw do
  resources :books, only: [:index, :show] do
    post 'download'
  end

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]

  validates :title, :url, presence: true, uniqueness: true
  validates :slug, uniqueness: true

  def self.search(title)
    where('title ILIKE :title OR description ILIKE :title', title: "%#{title}%")
  end

  private
    def uid
      SecureRandom.hex 2
    end

    def slug_candidates
      [
        :title,
        [:uid, :title]
      ]
    end

    def should_generate_new_friendly_id?
      title_changed? || slug.blank?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.search(params[:q]).page(params[:page]).order(id: :desc)
  end

  def show
    @book = Book.find(params[:id])
    AddViewToBookService.perform(@book.id)
  end

  def download
    AddDownloadToBookService.perform(params[:id]) if params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def urls(book)
    %w(pdf mobi epub).map do |type|
      content_tag :a,
        href: "#{book.url}#{type}",
        class: 'btn btn-primary download',
        data: { id: book.id } do
        content_tag :i, class: 'fa fa-cloud-download' do
          type.capitalize
        end
      end
    end.join(' ').html_safe
  end
end

app/views/books/_search_form.html.slim
.input-group.form-lg role="search"
  = form_tag(books_path, method: "get", role: "form", id:'search_form', enforce_utf8: false) do |f|
    = text_field_tag :q, params[:q], class: 'form-control', placeholder: "Some text"
  span.input-group-btn
    = submit_tag "Search", class: "btn btn-primary search_button"

app/views/books/index.html.slim
.space
section.bg-12.bg-center.bg-cover
  .bg-filter
    .container.section-lg
      h1.top-title Free books

section.section
  .container
    .simple-box
      = render 'search_form'
    .col-md-8.col-lg-9
      - @books.each do |book|
        .row.blog-post.wow.fadeInUp.animated
          .col-sm-6
            .hover-content
              .part-a.part-c
                p
                  .sapce-lg
                    h3= book.created_at.strftime('%d')
                    h3= book.created_at.strftime('%B')
              .part-b
                ul
                  li
                    i.fa.fa-clock-o.fa-fw
                    = book.created_at.to_formatted_s(:long)
                  li
                    i.fa.fa-eye.fa-fw
                    => book.views
                    | Views
                  li
                    i.fa.fa-cloud-download
                    => book.downloads
                    | Downloads
              = image_tag book.image, class: 'img-responsive'
          .col-sm-6
            = link_to book do
              h2= book.title
            p
              = book.description
            = link_to book, class: 'btn btn-default-trn-v2', title: "Download #{book.title} e-book" do
              i.fa.fa-angle-right
              | Go to download
      .row.text-center
        = paginate @books

app/views/books/show.html.slim
- meta title: @book.title
.space
section.section
  .container
    .col-lg-9
      h1= @book.title
      hr
      .row
        p.col-lg-6
          b Views: &nbsp;
          = @book.views
        p.col-lg-6
          b Downloads: &nbsp;
          = @book.downloads
      hr
      p.description
        = @book.description
      hr
      .tags
        ul.list-unstyled
          = urls(@book)
    .col-lg-3
      = image_tag @book.image
      .addthis_sharing_toolbox

app/views/layouts/_footer.html.slim
a.back-to-top href="#" 
  i.fa.fa-angle-up
/! Footer
footer.footer
  .footer-top
    .container
      .row
        .col-md-4.col-lg-4.col-sm-12.col-xs-12
          h4 Contact
          ul.info-list.md-list.i-primary
            li
              = mail_to "maxim.djuliy@gmail.com" do
                | maxim.djuliy@gmail.com
        .space-sm.visible-sm.visible-xs
        .col-md-4.col-lg-4.col-xs-12
          h4 Hosted on
          = link_to 'https://goo.gl/ffq1pg', rel: "nofollow", target: '_blank' do
            = image_tag  'digitalocean-badge-gray.png', class: 'text-center', alt: 'We hosted on DigitalOcean', title: 'We hosted on DigitalOcean'
        .space-sm.visible-sm.visible-xs
        .col-md-4.col-lg-4.col-xs-12
          h4 Find me on
          ul.circle-icons.icons-list
            li
              a href="https://github.com/max-si-m" title="Follow us" rel="nofollow" target='_blank'
                i.fa.fa-github
            li
              a href="https://twitter.com/max_si_m" title="Follow us" rel="nofollow" target='_blank'
                i.fa.fa-twitter
            li
              a href="https://www.linkedin.com/in/maximdjuliy" title="Follow us" rel="nofollow" target='_blank'
                i.fa.fa-linkedin-square
  .footer-bottom
    .container
      p &copy; 2016 Just for fun

app/views/layouts/_navigation.html.slim
/! Navigation
nav#navbarSettings.navbar.navbar-default.navbar-fixed-top role="navigation"
  .container
    .navbar-header
      button.navbar-toggle data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        ' Packtpub
        span.text-primary Free Books
    /!bs-navbar-collapse-1.collapse.navbar-collapse
      #ul.nav.navbar-nav.navbar-right
        #li.dropdown
          #= link_to "Home", "#"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0" name="viewport" /
    = metamagic
    link href="https://fonts.googleapis.com/css?family=Lato:300,400" rel="stylesheet" /
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    link href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.1.1/animate.min.css" rel="stylesheet" /
    script src="//cdnjs.cloudflare.com/ajax/libs/wow/0.1.6/wow.min.js" 
    script src="//cdn.jsdelivr.net/jquery.knob/1.2.9/jquery.knob.min.js" 
    script src="//cdnjs.cloudflare.com/ajax/libs/mixitup/1.5.6/jquery.mixitup.min.js" 
    script src="//cdn.jsdelivr.net/jquery.sticky/1.0.0/jquery.sticky.min.js" 
    script src="//cdn.jsdelivr.net/jquery.nicescroll/3.5.4/jquery.nicescroll.min.js" 

  body
    = render 'layouts/navigation'
    = yield
    = render 'layouts/footer'
    script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-56ee7ec30bd6c4c0"